#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Rivulet\Console\Console;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$console = new Console();
$console->run();